using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AvaloniaSourceGenerators;

internal static class CodeAnalysisExtensions
{
    extension(INamedTypeSymbol namedTypeSymbol)
    {
        public bool Is(string baseTypeName)
        {
            if (namedTypeSymbol.IsType(baseTypeName))
            {
                return true;
            }

            if (namedTypeSymbol.IsInterface(baseTypeName))
            {
                return true;
            }

            return false;
        }

        public bool IsType(string baseTypeName)
        {
            var baseType = namedTypeSymbol.BaseType;
            while (baseType != null)
            {
                if (baseType.ToDisplayString() == baseTypeName ||
                    baseType.ToDisplayString().EndsWith($".{baseTypeName}"))
                {
                    return true;
                }

                baseType = baseType.BaseType;
            }

            return false;
        }

        public bool IsInterface(string interfaceName)
        {
            var interfaces = namedTypeSymbol.Interfaces;
            foreach (var @interface in interfaces)
            {
                if (@interface.ToDisplayString() == interfaceName ||
                    @interface.ToDisplayString().EndsWith($".{interfaceName}"))
                {
                    return true;
                }

                if (@interface.Is(interfaceName))
                {
                    return true;
                }
            }

            return false;
        }
    }

    extension(MemberDeclarationSyntax memberDeclarationSyntax)
    {
        public T? As<T>() where T : MemberDeclarationSyntax
        {
            return memberDeclarationSyntax as T;
        }
    }

    extension(ClassDeclarationSyntax classDeclarationSyntax)
    {
        public string Output(string ns, bool nullable, params string[] usings)
        {
            return SyntaxFactory.FileScopedNamespaceDeclaration(SyntaxFactory.ParseName(ns))
                .AddMembers(classDeclarationSyntax).Output(nullable, usings);
        }
    }

    extension(BaseNamespaceDeclarationSyntax baseNamespaceDeclarationSyntax)
    {
        public string Output(bool nullable, params string[] usings)
        {
            return SyntaxFactory.CompilationUnit()
                .AddUsings(usings.Select(u => SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(u))).ToArray())
                .AddMembers(baseNamespaceDeclarationSyntax).Output(nullable);
        }
    }

    extension(CompilationUnitSyntax compilationUnitSyntax)
    {
        public string Output(bool nullable)
        {
            var builder = new StringBuilder();
            builder.AppendLine(@"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
");

            builder.AppendLine();
            if (nullable)
            {
                builder.AppendLine("#nullable enable").AppendLine();
            }

            builder.AppendLine(compilationUnitSyntax.NormalizeWhitespace().ToFullString());
            return builder.ToString();
        }
    }
}